# Generated by Django 3.0.3 on 2020-02-22 13:10

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.FileField(upload_to=content.models.file_prefix('doc')),
        ),
    ]
